package com.stehno.effigy.repository

/**
 * Optional helper interface providing the default CRUD method definitions generated by Effigy. This is mostly useful for making
 * your IDE happy - it is not required by the framework, the methods will exist either way.
 */
interface CrudOperations<E, K> {

    /**
     * Persists the new entity in the database. The ID value will be returned and also updated on the
     * entity instance passed into the method.
     *
     * @param entity
     * @return
     */
    K create(E entity)

    E retrieve(K entityId)

    List<E> retrieveAll()

    void update(E entity)

    /**
     * Deletes the entity with the given id. If no entity exists with the given id, no action will be taken. A value of true or false
     * will be returned based on whether or not an entity was actually deleted.
     *
     * @param entityId the entity id
     * @return a value of true if an entity was actually deleted
     */
    boolean delete(K entityId)

    boolean deleteAll()
}